### ISSUE TITLE
# borgmatic - No valid configuration files found

### ISSUE THREAD

**Issue by bbbenji** [knthmn/docker-borgmatic-rclone#5]
Attempting to run `borgmatic` within the container returns an error because a config is not located.

```
/ # borgmatic
/etc/borgmatic/config.yaml /etc/borgmatic.d /root/.config/borgmatic/config.yaml /root/.config/borgmatic.d: No valid configuration files found

summary:
/etc/borgmatic/config.yaml /etc/borgmatic.d /root/.config/borgmatic/config.yaml /root/.config/borgmatic.d: No valid configuration files found

Need some help? https://torsion.org/borgmatic/#issues
```

As a quick fix I mounted my config directory to `/etc/borgmatic/`
```
- $PERSIST/borgmatic-rclone/borgmatic:/etc/borgmatic:ro
```

This is only an issue if attempting to, for example, restore a backup. Otherwise, the container itself works fine.

**Comment by knthmn** [comment]
The issue is the directory storing borgmatic config files is mounted to `/mnt/borgmatic/` instead of the default `/etc/borgmatic.d`. When the script runs borgmatic, it manually specifies the directory by using `-c`.

Now I realized that I should have used `/etc/borgmatic.d` all along. Sadly there is no environmental variable to set that can change the default directory borgmatic uses. If I change the directory now, I risk breaking people's setup. Maybe I can deprecate `/mnt/borgmatic` by still running configurations in it with a warning in logs. Any suggestions?

**Comment by bbbenji** [comment]
Perhaps a symbolic link is enough?

**Comment by bbbenji** [comment]
Or maybe submit a PR upstream to https://github.com/witten/borgmatic with the possibility of defining a config dir via environmental variable.

Seems it would be a useful feature anyway.

**Comment by knthmn** [comment]
Yes I totally forgot about symbolic link. I have tested it and it worked. I will also see if I can do the same for rclone's config and push out a patch tmr.
